#模式 balance(均衡模式)、parallel(平行模式)
mode: balance
#容器
containers:
  #青龙
    #类型
  - type: ql
    #面板地址
    address: http://192.168.31.233:5700
    #用户名
    username: admin
    #密码
    password: admin
    #权重 balance模式下权重越高分得的ck越多
    weigth: 3
    #单独对容器进行模式设置
    mode: parallel
  # - type: ql
  #   address: http://192.168.31.233:5525
  #   username: admin
  #   password: admin
  #   weigth: 2
  # #V4面板
  # - type: v4
  #   #配置文件路径
  #   path: /Users/cdle/Desktop/jd_study/jdc/config.sh
  #   weigth: 1
  # #不知名面板
  # - type: li
  #   path: /Users/cdle/Desktop/jd_study/jdc/list.sh
  #   weigth: 5
#自定义二维码页面，支持本地、网络路径
qrcode: https://ghproxy.com/https://raw.githubusercontent.com/cdle/jd_study/main/jdc/theme/sakura.html
#静态文件 便于自定义二维码页面时，引入css、js等文件
static: ./static
#管理员账户pin，有多个用'&'拼接
master: 
