name: jdc
on:
  schedule:
    - cron: 10 */2 * * *
  watch:
    types: started
jobs:
  build:
    runs-on: Ubuntu-20.04  
    steps:
    - uses: actions/checkout@v2
    - name: down
      run: |
        shopt -s extglob
        rm -rf !(README.md)
        shopt -u extglob
        git clone https://github.com/cdle/jd_study.git  ./jd_study
        cp -rf ./jd_study/jdc/* ./
        rm -rf ./jd_study
        CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -o JDCarm
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o JDCarm64
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o JDCamd64
        CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o JDCamd64.exe
    - name: 'Commit Files'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am 'update'
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: main
